### ISSUE TITLE
Cannot connect to already running IDE instance. Exception: Process 2 is still running

### ISSUE THREAD

**Issue by Snowbridge** [flathub/com.jetbrains.DataGrip#103] opened 2023-08-23 06:53 UTC
A couple days ago DataGrip has updated and is unable to start since then.

```console
lms@lms-ubuntu:~$ head -n 4 /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
lms@lms-ubuntu:~$ uname -a
Linux lms-ubuntu 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
lms@lms-ubuntu:~$ flatpak list --app | grep Grip
DataGrip	com.jetbrains.DataGrip	2023.2.1	stable	system
```
That's what I get, running from terminal:
```console
lms@lms-ubuntu:~$ flatpak run com.jetbrains.DataGrip
[0.001s][warning][perf,memops] Cannot use file /tmp/hsperfdata_lms/2 because it is locked by another process (errno = 11)
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true

Start Failed
Cannot connect to already running IDE instance.
Exception: Process 2 is still running
WARN: <resource-bundle>messages.DataGripBundle</resource-bundle> tag is found in an xml descriptor included into the platform part of the IDE but the platform part uses predefined bundles (e.g. ActionsBundle for actions) anyway; this tag must be replaced by a corresponding attribute in some inner tags (e.g. by 'resource-bundle' attribute in 'actions' tag)
Gtk-Message: 09:35:18.266: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:35:18.266: Failed to load module "canberra-gtk-module"
```
There is no `/tmp/hsperfdata_lms` directory. Tried to create the `/tmp/hsperfdata_lms/2`, but made no difference: the error message is the same and the directory `/tmp/hsperfdata_lms` vanished after `flatpak run`.

Solved by downgrading to 2023.1.2 (tried also previous 2023.2, but it's broken either):

```console
lms@lms-ubuntu:~$ sudo flatpak update --commit=65cdd322fd9fffbad5b0a0108225c4593aa85ccf49ec9ae11640e21caf87ad4c com.jetbrains.DataGrip
```

**Comment by x80486** [comment] 2023-08-25 16:41
Problem is that [this does not seem directly](https://intellij-support.jetbrains.com/hc/en-us/community/posts/10865358461202-Intellij-cannot-launch-because-process-2-already-running) related with the `Flatpak` distribution. It looks like it's something in the `JetBrains` core distribution — shared by the tools.

I have the `Ultimate` version running in a VM and it happens sometimes, though I've never had a problem that it doesn't start again.

**Comment by nikodunk** [comment] 2023-09-20 16:42
I have the same problem! Haven't been able to start since I updated a few days ago.

The one thing that helped was removing the Flatpak and (and critically all it's data!!) and then it works shortly, before _again_ starting to throw above error.

**Comment by x80486** [comment] 2023-09-20 18:04
You don't need to remove the entire `config` sub-directory, but just the `.lock` file.

**Comment by nikodunk** [comment] 2023-09-21 08:35
Smart. Well removing the `.lock` file only is way better solution - thank you @x80486 :D

**Comment by nikodunk** [comment] 2023-09-21 18:11
Confirmed! Removing `.lock` file from  `/home/your_user/.var/app/com.jetbrains.DataGrip/config/JetBrains/DataGrip2023.2` did the trick. I think the issue is that there is a `.../config/JetBrains/DataGrip2023.1` issue too, which was probably causing some kind of "remove .lock from wrong place" situation? Or maybe this is normal when upgrading versions. Thank you very much for your help @x80486 @Snowbridge !

**Comment by x80486** [comment] 2023-09-21 18:14
This started happening around February/March. I think they should be able to fix it at some point.

I'll close this issue because it's not really related directly with the Flatpak format.

**Closed by x80486** 2023-09-21 18:14 UTC
